### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by SteelAlloy** [grasilife/github-pages-deploy-action#1] opened 2020-03-07 23:34 UTC
**Describe the bug**

Build and deploy fail

**Reproduce**

```
Run grasilife/github-pages-deploy-action@master
  env:
    ACCESS_TOKEN: ***
    BASE_BRANCH: master
    BRANCH: gh-pages
    FOLDER: build
    CNAME: www.secure-rm.com
    BUILD_SCRIPT: npm install && npm run build
/usr/bin/docker run --name e87b5279380b952cd04ce98f657105bb99907a_3a657a --label e87b52 --workdir /github/workspace --rm -e ACCESS_TOKEN -e BASE_BRANCH -e BRANCH -e FOLDER -e CNAME -e BUILD_SCRIPT -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/docs/docs":"/github/workspace" e87b52:79380b952cd04ce98f657105bb99907a
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Expected behavior**

Here is my file, am I doing things wrong?

```yaml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: grasilife/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        CNAME: www.secure-rm.com
        BUILD_SCRIPT: npm install && npm run build # The build script the action should run prior to deploying.
```

**Comment by SteelAlloy** [comment] 2020-03-10 21:25
I've used Jenkins instead.

**Comment by tillsanders** [comment] 2020-03-11 22:11
Good for you, but the issue is still valid. I am experiencing the exact same problem.

**Comment by tillsanders** [comment] 2020-03-11 22:15
Thank you 👍

**Comment by xavierfoucrier** [comment] 2020-10-30 10:28
The issue is still here in October...
@grasilife, @JamesIves any chance to fix it soon? thx :wink:

**Comment by JamesIves** [comment] 2020-10-31 00:30
This issue is months old and based on a previous major version. Please create a new issue.

**Comment by xavierfoucrier** [comment] 2020-10-31 14:14
Hi @grasilife,

I have opened a new issue as you suggested, #2.
You can close this one :wink: 

Thanks!

**Comment by JamesIves** [comment] 2020-10-31 14:38
> The issue is still here in October...
> @grasilife, @JamesIves any chance to fix it soon? thx 😉

This is a fork of a project I maintain, sorry.

**Comment by xavierfoucrier** [comment] 2020-10-31 14:39
> > The issue is still here in October...
> > @grasilife, @JamesIves any chance to fix it soon? thx wink
> 
> This is a fork of a project I maintain, sorry.

No problem @JamesIves, I have created another issue as @grasilife suggested.
Thanks for your answer :wink:

**Comment by JamesIves** [comment] 2020-10-31 14:46
I'd probably suggest switching to the new version if you want updates, the last update to this repo was in 2019 and GitHub has deprecated a fair amount of stuff since then. 

https://github.com/JamesIves/github-pages-deploy-action

**Comment by xavierfoucrier** [comment] 2020-10-31 15:07
@JamesIves WOW :tada: ... I am switching right now! :smiley:

**Comment by xavierfoucrier** [comment] 2020-10-31 15:23
Big thanks @JamesIves, that's perfectly works for me!

**Comment by xavierfoucrier** [comment] 2020-10-31 15:29
@tillsanders just to let you know that this issue is fixed on [the official Github project](https://github.com/JamesIves/github-pages-deploy-action).
@oganexon you may close the issue.
@grasilife if this project is no more maintained, please archive it and update the readme appropriately.

**Closed as completed** 2020-10-31 17:33 UTC
